### ISSUE TITLE
Major Priority!!! (P1) Username shows email not verified when it was verified Please check code

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#13]
![username email verification issue](https://user-images.githubusercontent.com/34143768/36916895-1af2a176-1e0a-11e8-9951-c59014be72fb.jpeg)

Password: Ashley2005%

**Comment by pxlsz** [comment]
I have logged in using this login details username : richardl2465 password: Ashley2005%

**Comment by urentmellc** [comment]
Still a major problem, for user richardl2465, Password123@ I sent a reverification email and clicked it still showing not verified when attempting to login.... This must be fixed we will lose business... Please fix on your Sat please. 
![emailnotverifiedwhenithas](https://user-images.githubusercontent.com/34143768/37177048-12d5b992-22d3-11e8-9a6c-d9c4dd12af59.jpeg)
![richardl2465emailverification](https://user-images.githubusercontent.com/34143768/37177085-3c739c24-22d3-11e8-9bbf-090b6ecee739.jpeg)

**Comment by Jayantapixel** [comment]
Please provide email id and password of the so we can check re-sending the same from admin. Using our email, its working smoothly.

**Comment by pxlsz** [comment]
Done.
