### ISSUE TITLE
(P1) In Admin Panel, we need to be able to resend verification emails to all users if Asked

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#14]

**Comment by Jayantapixel** [comment]
This is require time to develop. Will do tomorrow.

**Comment by pxlsz** [comment]
Done

**Comment by urentmellc** [comment]
where is this completed so I can verify in the admin panel?

**Comment by Jayantapixel** [comment]
Its showing in member section as reply icon. Please check and close if all ok.

**Comment by urentmellc** [comment]
Was tested to ensure it works after Development for it?
		
		

		Get Outlook for iOS
	




On Wed, Mar 7, 2018 at 11:47 AM -0800, "Jayanta Chatterjee" <notifications@github.com> wrote:












Its showing in member section as reply icon. Please check and close if all ok.

**Comment by Jayantapixel** [comment]
Yes its tested and you can test it sending you the same from admin panel. Kindly close this issue.
