### ISSUE TITLE
*P1,Important*, FB Pixel Code Script, Please Install Script Immediately

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#18]
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '1994694197517806');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=1994694197517806&ev=PageView&noscript=1"
/></noscript>

**Comment by pxlsz** [comment]
We have added this script in header.

**Comment by urentmellc** [comment]
ok marketing is checking now... will close one confirmed working

**Comment by urentmellc** [comment]
I was informed you installed the new script however you still left the old script in place. Please only have this one that was sent as the FB pixel. Please confirm this is understood.

**Comment by pxlsz** [comment]
Please ask your marketing team to check properly. They may getting it from their browser cache. Check the attached image so you/your marketing people can understand the fb pixel code has been changed. We haven't get any old code in the page. You can also view that from the browser, view source.
![fbpixel](https://user-images.githubusercontent.com/28383353/37136156-67551358-22c6-11e8-9e60-7a2a006eeade.png)

**Comment by urentmellc** [comment]
Ok will close issue for now and send to marketing...
