### ISSUE TITLE
*Priority*, Code Error Admin Panel Make Model ETC See pic

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#21]
saw this many times accessing listings in Admin Panel
![erroradminpanelitemmgmt](https://user-images.githubusercontent.com/34143768/37193051-3b69f554-231d-11e8-88a8-e80e1ece1dd9.jpeg)
![makemodelerroritemmgmt](https://user-images.githubusercontent.com/34143768/37193052-3b91e82a-231d-11e8-8431-719d4468b174.jpeg)

**Comment by pxlsz** [comment]
Done this issue.

**Comment by urentmellc** [comment]
when stating done please advise on what was completed...

**Comment by Jayantapixel** [comment]
Done means the issues which you raised has been corrected.
