### ISSUE TITLE
*Priority* Remove "ALL" Subscription Pages and Admin Panel Subscription 

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#24]
We have made a decision to remove the subscription option in its entirety from the site. Please remove the subscription page on the site and the controller for that on the admin panel. Any questions please ask. There should be nothing on the site relating to Subscription that I cannot control in the admin panel. Thank you.

**Comment by pxlsz** [comment]
We have removed subscription page from adminpanel and frontend.
