### ISSUE TITLE
*Priority*, Need URL Links for Marketing Company, Look

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#25]
1) I need the link (URL) for the Thank You page users see when they list their vehicle

2) The link  (URL) for the Thank You page after a user rents a recreational toy out

This should be self explanatory, please advise if you don't understand.

**Comment by pxlsz** [comment]
1. Thank you page for free item listing signup - https://urentme.com/greetings/thankyou_signupfree
2. Thank you page for user Signup - https://urentme.com/greetings/thankyou_signup
