### ISSUE TITLE
Upload New Video In Place of Current Video on How it Works Page

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#26]
I have sent you the link through Google drive to download and place on the site. Thank You.

**Comment by pxlsz** [comment]
We are try to add this video in how it works page. But video is not playing because browser didn't support mov format video. Please provide us mp4 format video.

**Comment by urentmellc** [comment]
new format video sent.... check your emails... please advise.

**Comment by pxlsz** [comment]
We have added this video in how it works page. Please check it.

**Comment by urentmellc** [comment]
Please place a link on the home page for How it Works... any questions please ask. 
		

		Get Outlook for iOS
	





On Mon, Mar 12, 2018 at 7:30 AM -0700, "pxlsz" <notifications@github.com> wrote:












We have added this video in how it works page. Please check it.
