### ISSUE TITLE
****Priority**** UPDATE REPOSITORIES ASAP FOR MY CODE!

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#29]
LAST UPDATE WAS 28 DAYS AGO... THIS NEEDS TO BE UPDATED IMMEDIATELY

1. the master branch needs to be updated after every task with a good description of the work.
2.DO NOT UPDATE PRODUCTION BEFORE UPDATING THE MASTER REPO!!!!!!

2.  I want the developer to do the following:
a. checkout a branch for our statement of work.

b. create the valid commits, and push up the changes to the master branch 

****so after every feature update I should be able to see the feature code updates in my repo on github

**Comment by pxlsz** [comment]
All latest files have been uploaded in Github. From now on-wards, we will update on regular basis as soon as we do any new changes and put comments on the changes.

**Comment by urentmellc** [comment]
Code still not showing updated... shows 28 days ago. Please update all files! Thank you.

**Comment by Jayantapixel** [comment]
You need to understand that only the updated files have been uploaded here. The files which wont updated will show old dates only. This is how repository system works.
