### ISSUE TITLE
~PRIORITY~,Users able to Open Account with Numbers, Unacceptable, See comments Below for Instructions

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#31]
this I mentioned before to Jayanta.
![userswithnumbers](https://user-images.githubusercontent.com/34143768/37558726-a1a83bf0-29d5-11e8-95c3-86ec025dc520.jpeg)

1)NO Users are allowed to become a member without putting in "ALL" information requested. Place a "*" in each field, requiring all fields to register an account with URentMe aside from using social media to do so. Please ask if you dont understand these instructions.

2)All Listings submitted need to be approved by Admin before being listed on our site Live! Please set this up that Admin/Admin Panel can approve or decline any listings and edit them as well. 

this needs to be completed please on your monday ready for investor presentations on my tuesday am.

**Comment by Jayantapixel** [comment]
Regarding point 1, please provide full screenshot so I can see which fields are blank. Also let me know what level of validation you want? Currently both in Signup and "Submit Free Listing" form, Name and user name is taking Numbers.

Regarding point 2, its a major change request. I will asked developer to work on this point on Monday and try to complete.

**Comment by urentmellc** [comment]
Hello Jayanta, regarding point 1 no one shall be allowed to sign up with numbers and but no other information in there at all and become a member. We need all fields to be in there Name and well and Username etc. No other way will be accepted. 
![shotof user](https://user-images.githubusercontent.com/34143768/37571319-81a10b50-2ab8-11e8-88de-78eb5774636a.jpeg)

Point 2 is imperative. We need to be able to have this so by my Monday am I would like this point handled as well as the other issues. Please make sure you understand this point or it will have to be redone again.

**Comment by Jayantapixel** [comment]
We are working on the validation of signup form and free listing form of website, but I found there is a chance to register from mobile app also which we cant check and correct now. We are putting a flag so in admin panel we can see from where the user is sign-up. We are correcting it in website.

**Comment by Jayantapixel** [comment]
Regarding point 1 (signup data issue):
We have corrected all the issues in website. So if somebody signup from website (through signup form OR Free listing), they need to fill-up the information. But user can signup from Android and iphone also and we haven't worked on that. We have just put an extra column in the admin so you can understand from where the signup happening so you can check if any issue is there on website or not. We can work on app issue only if we do the app work soon.

**Comment by urentmellc** [comment]
this must be done for mobile optiized versions for android and ios phones

**Comment by urentmellc** [comment]
<img width="1440" alt="screen shot 2018-03-19 at 8 14 15 am" src="https://user-images.githubusercontent.com/34143768/37604589-9003e7ee-2b4e-11e8-846c-8966a5dcad30.png">


This must Read the Following **Exactly** as Stated:
 
**Your Item is being verified for accuracy by our fantastic support team! Once it is approved your listing will appear on our Website and Mobile App. Please be prepared for qualified renters to contact you to start earning extra cash today! You may list as many items as you want, its FREE until we rent it out for You.**

**Comment by urentmellc** [comment]
Please manage your Paypal, Stripe, or Escrow.com accounts as Payment method is Required for your receipt of funds for your Rentals.

**Comment by Jayantapixel** [comment]
The text has been changed.
![changed-version](https://user-images.githubusercontent.com/35031627/37617592-9bae9ee6-2bd9-11e8-83c2-326a4a807f75.png)

**Comment by Jayantapixel** [comment]
Please close this.
