### ISSUE TITLE
~Priority Now, In Admin Panel there is nothing I see that shows me that I have a New Listing to Review and Accept~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#33]
Where in the admin panel is this? Where is my email notification stating there is a new listing submitted that needs review for acceptance? What email notification does the Owner see after listing? There must be a system in place that makes it easy for all. Please address this now and ask question not clear as it will likely be redone again. You must always see these things in addition to whats been asked.

**Comment by Jayantapixel** [comment]
As discussed and shown, all are there in the item listing page in admin. You have checked the flow also. But we need to put all pending items in dashboard as "Listing Pending Approval" which will lead item listing page with pending approval only. We will do it tomorrow and let you know.

**Comment by Jayantapixel** [comment]
We have added "Listing Pending Approval" functionality in dashboard which linked to Item Manager listing. Please check and close if its OK.
