### ISSUE TITLE
~Priority, Code Error in Admin Panel, Item Management when Deleting a Listing~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#37]
![codeerrorinadmindelete](https://user-images.githubusercontent.com/34143768/37694369-dfac3c48-2c83-11e8-8937-2abc2365b402.jpeg)

**Comment by pxlsz** [comment]
We have solved this issue. Please check once and close this issue.

**Comment by Jayantapixel** [comment]
Kindly close if you not getting any issues.
