### ISSUE TITLE
Changes to Insurance Page (2 Items)

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#38]
![insurancebolded](https://user-images.githubusercontent.com/34143768/37694480-cc56d45e-2c84-11e8-83ee-04c48028e780.jpeg) Please unbold this section as the other points are not bolded
![urentmeinsurance](https://user-images.githubusercontent.com/34143768/37694481-cc6ed1e4-2c84-11e8-84df-957d51fd076d.jpeg) For this one please have it like this: URentMe not Capital E on the end.

**Comment by pxlsz** [comment]
We have changed this image in insurance page. Please check and close it.

**Comment by urentmellc** [comment]
was not done still both the same...
<img width="1440" alt="screen shot 2018-03-21 at 8 25 40 pm" src="https://user-images.githubusercontent.com/34143768/37749635-1698ed06-2d46-11e8-85bb-3fda643c6bb0.png">

**Comment by Jayantapixel** [comment]
This is coming from your browser cache. Please clear cache and check. Or you can test in Chrome Incognito window. Check the attached screenshot.
![f4fcd790-0933-4df8-9933-795f2e4f9f73](https://user-images.githubusercontent.com/35031627/37755706-96537756-2dcc-11e8-8511-b5e54c5fb602.jpg)
