### ISSUE TITLE
~PRIORITY,Subscription Still Showing While Logged Into any Account~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#39]
Please see pic attached, no subscription should be part of this site or app ever. Please remove it from all aspects of the site. This still showing now. Verify its been done and advise please. 

![subsubscriptionstillshowsloggedin](https://user-images.githubusercontent.com/34143768/37916194-165b29d4-30d0-11e8-8daa-9856d92fbe44.jpeg)

**Comment by pxlsz** [comment]
We have corrected in website.
