### ISSUE TITLE
~Major Priority Fix NOW~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#42]
Please fix this now! This is showing on the site when someone submits a listing so please fix it now... thank you.

<img width="1440" alt="screen shot 2018-03-28 at 8 59 56 am" src="https://user-images.githubusercontent.com/34143768/38041409-7dee57dc-3266-11e8-9987-f7cd89f1cacf.png">

**Comment by Jayantapixel** [comment]
Issue have been resolved. Last day it was error in make model fields but now its image upload issue... taken care. Please check and close if it work at your end.
