### ISSUE TITLE
~ADMIN PANEL DELETING PHOTOS ISSUE~ NOT FIXED!!!

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#44]
AGAIN, DO NOT TELL ME ITS FIXED WHEN ITS NOT. THIS WAS ADDRESSED LAST WEEK AND ITS NOT WORKING. FIX IT NOW PLEASE!! MAKE SURE TO CHECK THAT ALL FUNCTIONALITY WHEN DELETING ACTUALLY WORKS! 
<img width="1440" alt="screen shot 2018-04-01 at 5 15 54 pm" src="https://user-images.githubusercontent.com/34143768/38178892-828ab11a-35d0-11e8-8eac-87df561bcb2f.png">

**Comment by pxlsz** [comment]
We have solved this issue. Please check it.

**Comment by Jayantapixel** [comment]
Please close if you opening new issues. Otherwise unnecessary the open issue are increasing.

**Comment by pixelphpdev** [comment]
Earlier was did it, if image id didn't match in database record, system through an error message that have to mentioned. We have changed it, If item image id don't match with database record then return in listing page and give an error message.
