### ISSUE TITLE
Remove this 

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#46]
<img width="1440" alt="screen shot 2018-04-02 at 8 34 12 am" src="https://user-images.githubusercontent.com/34143768/38202488-b89e3d46-3650-11e8-8424-9a8f873e364c.png">

**Comment by urentmellc** [comment]
Remove the resolution issue allow photos to be uploaded that are larger in size ask if you dont understand this.

**Comment by pixelphpdev** [comment]
We have removed this validation. Now you can upload item image from admin panel.

**Comment by Jayantapixel** [comment]
Also, don't ask us to revert back as an issue, since now any size of images can be uploaded in your server.

**Comment by Jayantapixel** [comment]
Yes, its done on both admin and front end.

**Comment by Jayantapixel** [comment]
Please close.
