### ISSUE TITLE
~NEW CODE ERROR SENDING EMAIL FROM ADMIN PANEL TO OWNER~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#48]
WHEN I ATTEMPT TO SEND AN EMAIL IT SHOWS ME THIS ERROR... FIX IT. AND TEST IT NUMEROUS TIMES BEFORE ADVISING ME. 

<img width="1440" alt="screen shot 2018-04-03 at 2 12 28 pm" src="https://user-images.githubusercontent.com/34143768/38276242-34f5e8f0-3749-11e8-9621-2068c8e67c09.png">
<img width="1440" alt="screen shot 2018-04-03 at 2 12 18 pm" src="https://user-images.githubusercontent.com/34143768/38276243-351095ba-3749-11e8-9ea0-c2002eab0857.png">

**Comment by Jayantapixel** [comment]
Reason for this error is as follows:
The user have been registered through Android app without any email id. Please be sure that user has email id before sending email to him since your mobile apps are still erroneous. Though we have put some validation so you cant send email unless he has email.
