### ISSUE TITLE
Subscription Limitation on Listings 

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#5]
Anyone should be able to submit as many listings as they want to for free without choosing a subscription/payment method. Currently only 1 is allowed and then you are prompted to purchase a subscription in the flow. Regardless of how a Owner chooses to pay he should only be prompted for payment method either % of rental amount or subscription method into doing so when a successful listing is completed. All owners should have managed payment preferences in their account still. Any questions please ask. Thank you.

**Comment by pxlsz** [comment]
Done this point.

**Comment by urentmellc** [comment]
I will check and advise.
