### ISSUE TITLE
~ADD VIN/HULL ID # TO SUBMIT FREE LISTING AND IN THE ADD A LISTING FIELD IN YOUR ACCOUNT

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#50]
PLEASE ADD THIS MANDATORY FIELD AS STATED, PLEASE ASK IF YOU HAVE ANY QUESTIONS REGARDING THIS. JAYANTA IS AWARE OF WHAT I NEED. THANK YOU.

**Comment by pixelphpdev** [comment]
We have added this field in submit free listing form, List an item form and admin edit item form. Also  VIN/HULL ID is showing in item details page.
