### ISSUE TITLE
~HOW IT WORKS PAGE, ADD TABS ON THE PAGE TO OPEN TO ADDITIONAL CONTENT~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#51]
PLEASE ADD THE FOLLOWING TABS **LEFT JUSTIFIED** WITHIN THE PAGE AFTER THE VIDEO SO THAT I CAN FILL IN THE CONTENT MYSELF IN THE ADMIN PANEL. PLEASE MAKE IT GRAPHICALLY THE SAME.

**TABS**
RENTAL PROCESS 
ELIGIBILITY 
DEPOSITS 
DAMAGE 
FEES 
CANCELLING 
RENTER TERMS
OWNER TERMS
SAFETY

**Comment by Jayantapixel** [comment]
This is done. We have created a separate menu for tab content. You can update tab content from the list. Even you can add new tab also. Please check and confirm if any issue.

**Comment by Jayantapixel** [comment]
Video is running fine here. Made the W in caps. Please clear browser and check again.
![image](https://user-images.githubusercontent.com/35031627/38372113-b2b9a704-390b-11e8-993a-a2ff5079c974.png)

**Comment by urentmellc** [comment]
REMOVE THE BLUE OUTLINE ON THE FIRST TAB MAKE SURE IT IS THE SAME THROUGHOUT

<img width="1440" alt="screen shot 2018-04-05 at 9 28 27 am" src="https://user-images.githubusercontent.com/34143768/38378818-b8571ec4-38b3-11e8-8fd1-996b8742f568.png">

**Comment by urentmellc** [comment]
another issue found is when editing content in the admin panel its not generating properly on the front end. No formatting is working with bullets etc.. check it out and fix it. Thank you. 

<img width="1440" alt="screen shot 2018-04-05 at 9 32 20 am" src="https://user-images.githubusercontent.com/34143768/38379016-4409dcd6-38b4-11e8-8334-f6ddbe3fe85d.png">

**Comment by urentmellc** [comment]
if you notice some text is highlighted in blue and some not, not sure whats up here but remove all highlighting... should be a quick change

<img width="1440" alt="screen shot 2018-04-05 at 9 45 04 am" src="https://user-images.githubusercontent.com/34143768/38379600-0f180b68-38b6-11e8-8671-d25d42c18113.png">

**Comment by urentmellc** [comment]
Please figure out why none of the font, boldness works and doesnt work from the admin panel. I want to be able to adjust the boldness and insert bullets which it doesnt do just blue highlights when you select bullet points. In whole I need to be able to do all editing/proofreading in the back end and have it properly save on the front end which its not doing. Please fix this.

<img width="1440" alt="screen shot 2018-04-05 at 12 35 35 pm" src="https://user-images.githubusercontent.com/34143768/38387790-e3b5ea72-38cd-11e8-86bb-8249638c5fe6.png">

**Comment by Jayantapixel** [comment]
All changes done. Please check and confirm if any more changes require in this page.
