### ISSUE TITLE
~Place Rental Contract that is downloadable in PDF in all Owners My Account Documents ~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#53]
See attached pdf file... only use Page 2! Do not use page 1... Please confirm receipt and understood. Thank you.
[RentalLtr18.pdf](https://github.com/pixelphpdev/urentme/files/1895970/RentalLtr18.pdf)

**Comment by pixelphpdev** [comment]
We have added pdf file in My Account Document page.
