### ISSUE TITLE
~MAJOR PRIORITY,About Us, Content Page Missing now from Admin Panel~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#54]
This used to be there and editable in the back end the About Us page... This needs to be active and editable from the back end as it was before now its gone. This is major priority and needs to be done asap over the weekend if necessary.

**Comment by Jayantapixel** [comment]
For time being, if you want to change text in About Us, just pit following URL in browser after login,
https://urentme.com/admin/pages/edit/1

We will add it in listing on Monday when developer will back to office.

**Comment by urentmellc** [comment]
Please ensure its up and editable on your Monday am.

**Comment by pixelphpdev** [comment]
We have added in content page listing and content have updated from back end.
