### ISSUE TITLE
~VIN # Issue, Mandatory~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#55]
You placed this tab there however people can put any default # in there... there are 17 numeric digits maximum, you cannot allow any alpha fields only, it has to be a valid vin/hull id. They cannot enter a listing without it. Also place a ? with a circle that will pop up when there mouse hovers over it, "We need this information for Insurance Purposes and to provide you with the Proper Coverage"

Please ask if you dont understand!!!!

**Comment by Jayantapixel** [comment]
Please send an actual number so we can understand the format. Validation can only be completed if you integrate with any API which provide valid VIN. Max number of numeric, should not be a character etc we can do. The field is already compulsory.

**Comment by urentmellc** [comment]
Here is an example of a VIN/Hull ID/RV/Etc, **1G1YT2D63F5601394**. Make sure you understand this... also need what I stated with the ? and bubble with that info. Ask questions and test it thoroughly before telling me its done. I need this working your Monday.

**Comment by urentmellc** [comment]
No one should be allowed to enter a listing without a VIN # period. No exceptions.

**Comment by Jayantapixel** [comment]
Following validation have been implemented:
1. VIN number should be 17 Characters long
2. The VIN is alpha-numeric. ONLY alphabet or ONLY numeric is not allowed. Its a combination of digits and capital letters
3. Its a compulsory field. Without filling it, user will not be able to enter item.

Please check if above working at your end and let me know if you want any more validation.

**Comment by Jayantapixel** [comment]
Yes we did. Please check.

**Comment by urentmellc** [comment]
Vin doesnt work as asked.. tried to enter it in with a valid vin not working... see pic attached with error...

<img width="1440" alt="screen shot 2018-04-16 at 9 31 06 am" src="https://user-images.githubusercontent.com/34143768/38822645-ee8726bc-4158-11e8-9654-9dfbb105f7d7.png">

**Comment by urentmellc** [comment]
ok i see you did this in the submit free listing screen not in my account screen when logged in. Can you make it my account screen as well for the same... also what I did was copy and paste the vin in that field and it didnt allow that.. I had to manually enter the vin. Can we allow copy and paste?

**Comment by Jayantapixel** [comment]
We have done in both. But when you copied it, may be a space has been added. We have tested and its working fine. Kindly check again.
