### ISSUE TITLE
~URM Blog Development, Site, Priority #1~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#56]
**URM - Blog Development Examples**
[](https://www.dropbox.com/sh/hz90wz1srikoejl/AAC1TJUUSijQJKQ1JihobVPUa?dl=0
)
In addition to sharing the above Dropbox link, please also share this description with them:

*********************

First off, thank you for serving as the developer of the website's new blog.  This blog should be created using a separate WordPress installation so that the blog can be easily managed through an Administrator account without need to access the main website. 

**The blog should be setup using the /blog domain - (ex: urentme.com/blog)**

The blog should be developed to take advantage of the functionality that WordPress provides natively so that new posts are automatically added to the main blog page.

The blog main page design should incorporate a two column display of the post image, with text overlayed on top of the images.  This should display 6 total blogs per page, with the ability to click on the numbers at the bottom to view past blogs.

The blog post page design should be single column and not use any sidebar, author or comments features.

If you would like to speak with me directly about the blog design, I hold office hours during IST from 8am - 10am Tuesday - Friday and can be reached via email at evan@tlgmarketing.com or on WhatsApp at 1-562-472-6362.

**Comment by Jayantapixel** [comment]
We have reviewed the design. We need to do the following to develop the same:

1. Need to create HTML of Blog and Article individual page as per the design sent
2. WordPress installation and configuration
3. Template integration of those pages in the WordPress

The above work require minimum 2.5 man days effort so cost would be $250.
We will add it in the time-sheet and can pay at the end of the month after completing the work.

Please approve, so we can proceed today itself.
