### ISSUE TITLE
~URM - Mouseflow Tracking Script~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#57]
Below is a link to a .txt document containing a snippet of JavaScript that your developer will need to add to the website before the </body> tag on the website:

https://www.dropbox.com/s/s619y50ljpfq704/URM%20-%20Mouseflow%20Code.txt?dl=0

**Comment by pixelphpdev** [comment]
We have added this script in header area. please see my screenshot.
![mouseflow-script](https://user-images.githubusercontent.com/36436777/38850689-1e4aa900-4230-11e8-8423-8f07328c8c33.png)
