### ISSUE TITLE
~Facebook Pixel Code, Please Install ASAP~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#58]
URM - Facebook Pixel Code - Please share with your website 

[](https://www.dropbox.com/s/dibl3gw4o4elz7r/URM-Facebook-Pixel.txt?dl=0
[]()https://www.facebook.com/business/help/314143995668266

**Comment by Jayantapixel** [comment]
This is installed in the site.
![image](https://user-images.githubusercontent.com/35031627/38937245-5e37fca0-4340-11e8-8182-432de5ba52d3.png)
