### ISSUE TITLE
Mobile Website Issues

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#6]
Please see screenshot of mobile website. For Make and Model every listing shows a number... This is incorrect based on the website, please fix this asap. Thanks.

**Comment by urentmellc** [comment]
![img_3663](https://user-images.githubusercontent.com/34143768/36827732-33362906-1cca-11e8-8a5e-048f75c29016.jpg)
see attached file in reference to the mobile web problem...

**Comment by pxlsz** [comment]
We have reviewed this issue and we are see same data is showing in both web and mobile. Also same data have added in adminpanel.
![admin-screen](https://user-images.githubusercontent.com/28383353/36894693-3d42a9e2-1e32-11e8-8335-5e1c5b41204f.png) 
![web-screen](https://user-images.githubusercontent.com/28383353/36894718-548677e6-1e32-11e8-8c8a-5750cc7a86d2.png)

**Comment by urentmellc** [comment]
this is a code design error then this needs to be fixed, I didnt enter numbers in the admin panel to get those results. Its needs to show proper make and model. Please review the submit quick listing and listing and item code as there is a problem and advise.

**Comment by urentmellc** [comment]
![mobileissue3218](https://user-images.githubusercontent.com/34143768/36912400-68b919f8-1dfb-11e8-9733-665dbc789034.jpeg)

**Comment by urentmellc** [comment]
again, this is what shows correctly in the admin panel for this specific listing.... this is a shot of the admin panel. this is what shows now on mobile. Its not fixed please fix now correctly. 
![image-1](https://user-images.githubusercontent.com/34143768/36912590-fb0747b2-1dfb-11e8-8c5c-d1ed98f10304.png)

**Comment by Jayantapixel** [comment]
Please close this since you have opened another one instead this.
