### ISSUE TITLE
~Tab Contents on How it Works~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#61]
please move down the first tab Rental Contract to last in the order, also you used to have a arrow that you clicked on each and them would expand the info after clicking. This was here and now its not. Provide an ability in the admin panel to be able to move the tabs in what order i select. Any questions please ask but this is easy.

<img width="1440" alt="screen shot 2018-04-19 at 5 32 01 pm" src="https://user-images.githubusercontent.com/34143768/39024731-9d85e162-43f7-11e8-83ec-2672cfa7a2fb.png">

**Comment by Jayantapixel** [comment]
1. rental Contract tab moved to the last one
2. In admin panel, you can change order of the tab. Functionality developed
3.  We have changed the hover and click option for left menu. Please check and confirm if you want in this way only.

**Comment by urentmellc** [comment]
This is fine however when creating hyperlinks for the tab contents they dont work please ensure that when a hyoerlink is created it actually goes to that specific tab. Thank you.
