### ISSUE TITLE
~VIN Info Feature~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#62]
<img width="1440" alt="screen shot 2018-04-22 at 6 28 29 pm" src="https://user-images.githubusercontent.com/34143768/39102687-f95a85b4-465a-11e8-9408-fdafd199533d.png">
The way we have the vin/hull id is ok for submitting a listing however it cannot be shown in the listing live. See screenshot. This is for admin info only not public and no other party needs to know this and is private info as the co only must know. Confirm you understand this and please fix this asap. Thank you.

**Comment by pixelphpdev** [comment]
We have removed vin/hull id from front-end. Now it is showing only back-end.
