### ISSUE TITLE
~Priority, Add Remarketing Code to the Website, See instructions Below~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#65]
Please ensure to read all below and all pages are tagged..... Thank you. 

**Add Remarketing Code to the Website**
Below is a link to download a .txt document that contains Google Remarketing code we need added to your company's website.  This code should be added before the end </body> tag every page of your website (including the blog).

URM - Remarketing Script
[](https://www.dropbox.com/s/i8bmntbf9po4xd5/URM-Remarketing-Code.txt?dl=0
)
Once this code is installed, we can begin tracking all of the visitors that come into your website, and can display them YouTube advertisements and banners across Google's Display Network.**

**Comment by Jayantapixel** [comment]
There is no link to download of the .txt document in above. Please repost..

**Comment by urentmellc** [comment]
https://www.dropbox.com/s/i8bmntbf9po4xd5/URM-Remarketing-Code.txt?dl=0

**Comment by pixelphpdev** [comment]
We have added remarketing script in head tag in urentme main site and blog site. Check the attached screenshot.

**Comment by pixelphpdev** [comment]
We have added remarketing script in head tag in urentme main site and blog site. Check the attached screenshot.
![google remarketing-script](https://user-images.githubusercontent.com/36436777/39416351-e80f890c-4c69-11e8-83e2-d347e0506bc7.png)
