### ISSUE TITLE
~DATES IN EMAIL TEMPLATES~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#69]
ALL EMAIL DATES SHALL BE LIKE THE FOLLOWING, 5/21/2018, NO TIME STAMP IS NECESSARY. THIS MUST BE THE FORMAT FOR ALL ON SITE.

**Comment by pixelphpdev** [comment]
We have changed date format in new booking email content. Please check the attach screenshot.
![email-date](https://user-images.githubusercontent.com/36436777/40050299-ad437666-5854-11e8-8dd5-fe15c0600f03.png)
