### ISSUE TITLE
Email Design Template

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#7]
Please see attached example of how I want the emails to look.. They now are not very professional and seem cheap. I will do the content please use this type of design with our logo etc.. 
![urentmeemail1](https://user-images.githubusercontent.com/34143768/36870277-64d17446-1d53-11e8-93eb-60beb66e844a.jpeg)
![emailurentme](https://user-images.githubusercontent.com/34143768/36870278-64fa6f90-1d53-11e8-93ab-c1fcdedebd66.jpeg)

**Comment by pxlsz** [comment]
We have changed email template as par your reference.

**Comment by urentmellc** [comment]
Ok will check and advise

**Comment by Jayantapixel** [comment]
Please close this, since same has been opened another.
