### ISSUE TITLE
~Last advisor for About Us Page~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#80]
Tim McCloud

Tim is a highly accomplished Senior Executive, Consultant, and Board Member with 16 years of success in technology, software, mobile devices across key B2C categories including gaming, ecommerce, education, social network, navigation, and entertainment. Leveraging extensive experience in data management, content creation, and customer acquisition, he has helped both early-stage startups and Fortune100 companies looking for acumen in data strategy and privacy, product development, SDLC, scaling, and growth. He leverages broad areas of expertise in international business; management consulting; data analysis, warehousing, and security; user privacy; digital, online, email, mobile, social media, interactive, and integrated marketing and advertising; geolocation/geospatial; predictive analytics/modeling; content strategy; SEO/SEM; demand gen; product management; go to market; Web and Google analytics; psychometrics; and business development.

In his executive career, Tim has held leadership positions at Adobe (Group Director, Mobile Product Marketing, Photoshop and Lightroom); Good&Co Labs (VP, Analytics, Product Marketing, B2C/B2B Growth); PlayKids (Global Director, Marketing and Analytics); Big Fish Games (Analytics Consultant); Life360 (Consultant, Use Acquisition); Playstudios (Director, User Acquisition, Mobile/Web); Electronic Arts (EA; Sr. Manager, SOCOM); Kabam (Sr. Manager, Acquisition); and Discovery Communications (Digital Advertising Account Manager).

Prior to joining the URentMe executive board, Tim helped restructure and optimize the marketing and analytics teams (2 out of 6 corporate teams) responsible for  both B2C and B2B products at StepStone gmbh and their subsidiary start-up Good&Co. While there, Tim also lead the design and implementation of analytics framework across all functions, including metric design, product/feature logging and reporting, A/B testing, and outcomes measurement. Owning the data science roadmap, he managed data pipeline and infrastructure to optimize reporting systems; maximizes statistical modeling and machine learning to generate profitable user acquisition and monetization; and executed advertising, social media, search, PR, mobile, and Web analytics. Using robust conversion funnels, Tim was able to drive 10k qualified leads prior to product launch.  

Previously at Adobe, as group manager over mobile products, Tim led the Adobe Creative Cloud team and collaborated with the Document Cloud and Marketing Cloud teams to develop and scale mobile engagement and subscriptions, launching new products including Photoshop Mix, Lightroom CC, Spark, Stock, Acrobat, Scan, and Adobe EDU. As global director of marketing and analytics of the 2nd largest telecom company in Brazil (and a strong education proponent and child privacy/well-being advocate), Tim worked assiduously on privacy regulatory/legal compliance, and on proper and sensitive restraints on marketing to children – critically influencing product development, launch, and management of the apps Playkids, Playkids Stories, Playkids Learn on the iOS, Android, watchOS, tvOS, PKOnline, and PKToys platforms.

![tmhsmay20183](https://user-images.githubusercontent.com/34143768/40759947-9f1c4d3e-6451-11e8-97d4-219e1e6b59b0.png)

**Comment by urentmellc** [comment]
Please add this to the about us page... thank you.

**Comment by Jayantapixel** [comment]
I feel you haven't seen the design. Its already added.

**Comment by urentmellc** [comment]
I cannot see it as its unable to open all... Once the design is complete in dev area I will check it, put it all in dev area for me to see

**Comment by Jayantapixel** [comment]
But in listing jpeg I can see him. Anyways lets wait ti  its implemented in dev area.

**Comment by urentmellc** [comment]
yes get it done so i can approve for live
